### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by TechTonicShift** [ContriHUB/SecurePix#1]
# 🚀Feature Request

### Description
*The UI looks mundane. Be creative and make a topic relevant and eye catchy UI. More creativity shall fetch you more points.*

**Comment by Devu0503** [comment]
@TechTonicShift can you assign me this issue

**Comment by TechTonicShift** [comment]
@Devu0503 You can start working on the issue.

**Comment by Devu0503** [comment]
@TechTonicShift  
 I have some issues in starting this project
I forked it open in codespace and according to the readme file i followed the steps to start it but was not able to start this project can you help me with that

**Comment by Ayush5071** [comment]
@TechTonicShift  sir, i've requested you for this issue , if it's already taken please cancel it on website so i can take any other issue

**Comment by Vaishnavi1047** [comment]
@TechTonicShift sir pls cancel this issue as by mistake i requested for it and it is already closed so that i can request for new one
