### ISSUE TITLE
Collaborative Features

### ISSUE THREAD

**Issue by TechTonicShift** [ContriHUB/SecurePix#2]
# 🚀Feature Request

### Description
*Adding functionality for collaborative file management (e.g., shared workspaces, version control for documents, and collaborative editing) would allow groups or teams to work together securely in real-time.*

**Comment by samimshoaib01** [comment]
sir i will try to work on it kindly assign it to me

**Comment by TechTonicShift** [comment]
@samimshoaib01 You can start working on the issue.

**Comment by samimshoaib01** [comment]
sir i think  Rinkeby, Ropsten are depreciated

**Comment by samimshoaib01** [comment]
tired sepolia and holesky but encountered this:
![image](https://github.com/user-attachments/assets/03483b34-39ad-4fcc-8d1f-0b94aa7e54d4)

**Comment by samimshoaib01** [comment]
It's solved by Sepolia Faucet

**Comment by samimshoaib01** [comment]
https://github.com/user-attachments/assets/5704e091-d8e3-45fe-b1a2-e4221dbae407

it says you don't have access and it doesn't function as shown is demo video.
And also its hard to understand from demo video due to low resolution video .

How to get rid of this ?

**Comment by samimshoaib01** [comment]
Sir kindly respond please

**Comment by TechTonicShift** [comment]
It seems like some of the blockchain and libraries also have been depreciated. This project will be removed for now once the website goes live and once the repo gets fixed the issues will be hosted again.
